// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YNABAutomationConsole.Data;

#nullable disable

namespace YNABAutomationConsole.Data.Migrations
{
    [DbContext(typeof(YnabDbContext))]
    [Migration("20260809190057_UseStringYnabTransactionIds")]
    partial class UseStringYnabTransactionIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YNABAutomationConsole.Categorization.CategorizationDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Consistency")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedPayee")
                        .HasColumnType("text");

                    b.Property<Guid>("ProcessedYnabTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProcessingRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RuleSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SampleSize")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SelectedCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedYnabTransactionId");

                    b.HasIndex("ProcessingRunId");

                    b.HasIndex("NormalizedPayee", "SelectedCategoryId");

                    b.ToTable("CategorizationDecisions");
                });

            modelBuilder.Entity("YNABAutomationConsole.Categorization.MerchantRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsExplicit")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedPayee")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedPayee", "IsExplicit")
                        .IsUnique();

                    b.ToTable("MerchantRules");
                });

            modelBuilder.Entity("YNABAutomationConsole.Categorization.PendingCategoryUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ProcessedYnabTransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedYnabTransactionId", "Status");

                    b.ToTable("PendingCategoryUpdates");
                });

            modelBuilder.Entity("YNABAutomationConsole.Categorization.ProcessedYnabTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CategorizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsInflow")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTransfer")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedPayee")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PayeeName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<string>("YnabTransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedPayee");

                    b.HasIndex("YnabTransactionId")
                        .IsUnique();

                    b.ToTable("ProcessedYnabTransactions");
                });

            modelBuilder.Entity("YNABAutomationConsole.Categorization.ProcessingRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AppliedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer");

                    b.Property<int>("FetchedCount")
                        .HasColumnType("integer");

                    b.Property<int>("ProposedCount")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ProcessingRuns");
                });

            modelBuilder.Entity("YNABAutomationConsole.Categorization.CategorizationDecision", b =>
                {
                    b.HasOne("YNABAutomationConsole.Categorization.ProcessedYnabTransaction", "ProcessedYnabTransaction")
                        .WithMany("Decisions")
                        .HasForeignKey("ProcessedYnabTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YNABAutomationConsole.Categorization.ProcessingRun", "ProcessingRun")
                        .WithMany()
                        .HasForeignKey("ProcessingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessedYnabTransaction");

                    b.Navigation("ProcessingRun");
                });

            modelBuilder.Entity("YNABAutomationConsole.Categorization.PendingCategoryUpdate", b =>
                {
                    b.HasOne("YNABAutomationConsole.Categorization.ProcessedYnabTransaction", "ProcessedYnabTransaction")
                        .WithMany("PendingUpdates")
                        .HasForeignKey("ProcessedYnabTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessedYnabTransaction");
                });

            modelBuilder.Entity("YNABAutomationConsole.Categorization.ProcessedYnabTransaction", b =>
                {
                    b.Navigation("Decisions");

                    b.Navigation("PendingUpdates");
                });
#pragma warning restore 612, 618
        }
    }
}
