// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using YNABAutomationConsole.Data;

#nullable disable

namespace YNABAutomation.Shared.Data.Migrations
{
    [DbContext(typeof(YnabDbContext))]
    [Migration("20260810130000_AddCategorizationDecisionDirection")]
    partial class AddCategorizationDecisionDirection
    {
    }
}